In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
startups = pd.read_excel("data/startup-expansion.xlsx")
startups.head()

,Store ID,City,State,Sales Region,New Expansion,Marketing Spend,Revenue
0,1,Peoria,Arizona,Region 2,Old,2601,48610
1,2,Midland,Texas,Region 2,Old,2727,45689
2,3,Spokane,Washington,Region 2,Old,2768,49554
3,4,Denton,Texas,Region 2,Old,2759,38284
4,5,Overland Park,Kansas,Region 2,Old,2869,59887

In [3]:
startups.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Store ID         150 non-null    int64
 1   City             150 non-null    str
 2   State            150 non-null    str
 3   Sales Region     150 non-null    str
 4   New Expansion    150 non-null    str
 5   Marketing Spend  150 non-null    int64
 6   Revenue          150 non-null    int64
dtypes: int64(3), str(4)
memory usage: 8.3 KB

In [4]:
startups.describe().round(2)

       Store ID  Marketing Spend   Revenue
count    150.00           150.00    150.00
mean      75.50          2893.15  39301.43
std       43.45           367.86  15465.75
min        1.00          1811.00  15562.00
25%       38.25          2662.25  21113.50
50%       75.50          2898.00  42993.00
75%      112.75          3111.50  51145.50
max      150.00          3984.00  68828.00

In [5]:
startups['Sales Region'].value_counts()

Sales Region
Region 2    86
Region 1    64
Name: count, dtype: int64

In [6]:
startups[startups['New Expansion']== "Old"].groupby("City").max()["Revenue"].nlargest(10)

City
Little Rock       68828
Grand Rapids      65475
Rochester         64906
Oxnard            64302
Fontana           63027
Providence        62337
Birmingham        60338
Overland Park     59887
San Bernardino    59870
Worcester         59840
Name: Revenue, dtype: int64

In [11]:
startups.groupby("New Expansion")[["City", "Revenue"]].max().nlargest(10, "Revenue")

                        City  Revenue
New Expansion
Old                  Yonkers    68828
New            Thousand Oaks    63148

In [12]:
startups.columns

Index(['Store ID', 'City', 'State', 'Sales Region', 'New Expansion',
       'Marketing Spend', 'Revenue'],
      dtype='str')

In [16]:
startups.sort_values(
    ["Revenue", "Marketing Spend"],
    ascending=[False, True]
)[["City",'New Expansion', "Revenue", "Marketing Spend"]].head(10)

               City New Expansion  Revenue  Marketing Spend
63      Little Rock           Old    68828             2440
31     Grand Rapids           Old    65475             2808
9         Rochester           Old    64906             2984
37           Oxnard           Old    64302             2318
146     Brownsville           New    63148             3675
17          Fontana           Old    63027             3085
139      Providence           Old    62337             3191
6        Birmingham           Old    60338             3110
4     Overland Park           Old    59887             2869
44   San Bernardino           Old    59870             3399

In [17]:
startups["Profit"] = startups["Revenue"] - startups["Marketing Spend"]

In [18]:
startups["Marketing ROI (%)"] = (
    startups["Profit"] / startups["Marketing Spend"]
) * 100

In [19]:
startups.head()

,Store ID,City,State,Sales Region,New Expansion,Marketing Spend,Revenue,Profit,Marketing ROI (%)
0,1,Peoria,Arizona,Region 2,Old,2601,48610,46009,1768.896578
1,2,Midland,Texas,Region 2,Old,2727,45689,42962,1575.430876
2,3,Spokane,Washington,Region 2,Old,2768,49554,46786,1690.245665
3,4,Denton,Texas,Region 2,Old,2759,38284,35525,1287.604204
4,5,Overland Park,Kansas,Region 2,Old,2869,59887,57018,1987.382363