In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
titanic = sns.load_dataset("titanic")

In [3]:
titanic.keys()

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [4]:
titanic.groupby("class").groups

{'First': [1, 3, 6, 11, 23, 27, 30, 31, 34, 35, 52, 54, 55, 61, 62, 64, 83, 88, 92, 96, 97, 102, 110, 118, 124, 136, 137, 139, 151, 155, 166, 168, 170, 174, 177, 185, 187, 194, 195, 209, 215, 218, 224, 230, 245, 248, 252, 256, 257, 258, 262, 263, 268, 269, 270, 273, 275, 284, 290, 291, 295, 297, 298, 299, 305, 306, 307, 309, 310, 311, 318, 319, 325, 329, 331, 332, 334, 336, 337, 339, 341, 351, 356, 366, 369, 370, 373, 375, 377, 380, 383, 390, 393, 412, 430, 434, 435, 438, 445, 447, ...], 'Second': [9, 15, 17, 20, 21, 33, 41, 43, 53, 56, 58, 66, 70, 72, 78, 84, 98, 99, 117, 120, 122, 123, 133, 134, 135, 144, 145, 148, 149, 150, 161, 178, 181, 183, 190, 191, 193, 199, 211, 213, 217, 219, 221, 226, 228, 232, 234, 236, 237, 238, 239, 242, 247, 249, 259, 265, 272, 277, 288, 292, 303, 308, 312, 314, 316, 317, 322, 323, 327, 340, 342, 343, 344, 345, 346, 357, 361, 385, 387, 389, 397, 398, 399, 405, 407, 413, 416, 417, 418, 426, 427, 432, 437, 439, 440, 443, 446, 450, 458, 463, ...], 'Third': [0, 2, 4, 5, 7, 8, 10, 12, 13, 14, 16, 18, 19, 22, 24, 25, 26, 28, 29, 32, 36, 37, 38, 39, 40, 42, 44, 45, 46, 47, 48, 49, 50, 51, 57, 59, 60, 63, 65, 67, 68, 69, 71, 73, 74, 75, 76, 77, 79, 80, 81, 82, 85, 86, 87, 89, 90, 91, 93, 94, 95, 100, 101, 103, 104, 105, 106, 107, 108, 109, 111, 112, 113, 114, 115, 116, 119, 121, 125, 126, 127, 128, 129, 130, 131, 132, 138, 140, 141, 142, 143, 146, 147, 152, 153, 154, 156, 157, 158, 159, ...]}

In [5]:
titanic.groupby("class").get_group('First')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [6]:
titanic.groupby("class")['survived'].count()

class
First     216
Second    184
Third     491
Name: survived, dtype: int64

In [8]:
titanic.groupby("sex")['age'].count()

sex
female    261
male      453
Name: age, dtype: int64

In [3]:
titanic.groupby(['sex','class']).get_group(('female','Third'))

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
863,0,3,female,NaN,8,2,69.5500,S,Third,woman,False,NaN,Southampton,no,False
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [5]:
titanic.groupby(['sex','class']).sum(numeric_only=True)

               survived  pclass      age  sibsp  parch       fare  adult_male  \
sex    class
female First         91      94  2942.00     52     43  9975.8250           0
       Second        70     152  2125.50     37     46  1669.7292           0
       Third         72     432  2218.50    129    115  2321.1086           0
male   First         45     122  4169.42     38     34  8201.5875         119
       Second        17     216  3043.33     37     24  2132.1125          99
       Third         47    1041  6706.42    173     78  4393.5865         319

               alone
sex    class
female First      34
       Second     32
       Third      60
male   First      75
       Second     72
       Third     264

In [10]:
titanic['mean_age'] = titanic.groupby(['sex','pclass'])['age'].transform('mean')
titanic['mean_age']

0      26.507589
1      34.611765
2      21.750000
3      34.611765
4      26.507589
         ...
886    30.740707
887    34.611765
888    21.750000
889    41.281386
890    26.507589
Name: mean_age, Length: 891, dtype: float64

In [11]:
titanic.age.fillna(titanic.mean_age)

0      22.00
1      38.00
2      26.00
3      35.00
4      35.00
       ...
886    27.00
887    19.00
888    21.75
889    26.00
890    32.00
Name: age, Length: 891, dtype: float64

In [13]:
from scipy.stats import zscore

In [15]:
titanic.groupby("pclass")['fare'].transform(zscore)

0     -0.546105
1     -0.164598
2     -0.488737
3     -0.397125
4     -0.478113
         ...
886   -0.572621
887   -0.692526
888    0.830727
889   -0.692526
890   -0.503610
Name: fare, Length: 891, dtype: float64

In [16]:
omlympic = pd.read_csv("data/olympics.csv")

In [17]:
omlympic.info()

<class 'pandas.DataFrame'>
RangeIndex: 29216 entries, 0 to 29215
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   City          29216 non-null  str
 1   Edition       29216 non-null  int64
 2   Sport         29216 non-null  str
 3   Discipline    29216 non-null  str
 4   Athlete       29216 non-null  str
 5   NOC           29216 non-null  str
 6   Gender        29216 non-null  str
 7   Event         29216 non-null  str
 8   Event_gender  29216 non-null  str
 9   Medal         29216 non-null  str
dtypes: int64(1), str(9)
memory usage: 2.2 MB

In [21]:
omlympic.groupby('City')['Medal'].value_counts()

City       Medal
Amsterdam  Bronze    242
           Silver    239
           Gold      229
Antwerp    Gold      497
           Silver    446
                    ...
Sydney     Silver    667
           Gold      663
Tokyo      Bronze    343
           Silver    337
           Gold      330
Name: count, Length: 66, dtype: int64

In [22]:
omlympic.keys()

Index(['City', 'Edition', 'Sport', 'Discipline', 'Athlete', 'NOC', 'Gender',
       'Event', 'Event_gender', 'Medal'],
      dtype='str')

In [23]:
omlympic.groupby('Edition')['Gender'].value_counts()

Edition  Gender
1896     Men        151
1900     Men        501
         Women       11
1904     Men        458
         Women       12
1908     Men        789
         Women       15
1912     Men        855
         Women       30
1920     Men       1255
         Women       43
1924     Men        833
         Women       51
1928     Men        615
         Women       95
1932     Men        555
         Women       60
1936     Men        791
         Women       84
1948     Men        718
         Women       96
1952     Men        750
         Women      139
1956     Men        739
         Women      146
1960     Men        737
         Women      145
1964     Men        820
         Women      190
1968     Men        819
         Women      212
1972     Men        947
         Women      238
1976     Men        924
         Women      381
1980     Men        958
         Women      429
1984     Men        973
         Women      486
1988     Men       1011
         Women      535
1992     Men       1105
         Women      600
1996     Men       1082
         Women      777
2000     Men       1126
         Women      889
2004     Men       1099
         Women      899
2008     Men       1110
         Women      932
Name: count, dtype: int64

In [24]:
titanic.pivot_table(index="sex", columns="pclass", values="fare")

pclass           1          2          3
sex
female  106.125798  21.970121  16.118810
male     67.226127  19.741782  12.661633

In [27]:
titanic.pivot_table(index=['sex','pclass'], aggfunc='sum',numeric_only=True)

               adult_male      age  alone       fare     mean_age  parch  \
sex    pclass
female 1                0  2942.00     34  9975.8250  3253.505882     43
       2                0  2125.50     32  1669.7292  2182.945946     46
       3                0  2218.50     60  2321.1086  3132.000000    115
male   1              119  4169.42     75  8201.5875  5036.329109     34
       2               99  3043.33     72  2132.1125  3319.996364     24
       3              319  6706.42    264  4393.5865  9198.133360     78

               sibsp  survived
sex    pclass
female 1          52        91
       2          37        70
       3         129        72
male   1          38        45
       2          37        17
       3         173        47

In [2]:
fifa = pd.read_csv("data/fifa.csv")

In [3]:
fifa.head()

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
2,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
3,200389,https://sofifa.com/player/200389/jan-oblak/20/...,J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,183277,https://sofifa.com/player/183277/eden-hazard/2...,E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3

In [4]:
fifa.set_index("short_name")[["height_cm", "weight_kg"]]

                   height_cm  weight_kg
short_name
L. Messi                 170         72
Cristiano Ronaldo        187         83
Neymar Jr                175         68
J. Oblak                 188         87
E. Hazard                175         74
...                      ...        ...
Shao Shuai               186         79
Xiao Mingjie             177         66
Zhang Wei                186         75
Wang Haijian             185         74
Pan Ximing               182         78

[18278 rows x 2 columns]

In [6]:
books = pd.read_csv("data/books.csv", on_bad_lines="skip")

In [9]:
books.head()

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,9/13/2004,Scholastic

In [10]:
books.columns

Index(['bookID', 'title', 'authors', 'average_rating', 'isbn', 'isbn13',
       'language_code', '  num_pages', 'ratings_count', 'text_reviews_count',
       'publication_date', 'publisher'],
      dtype='str')

In [13]:
books.pivot_table(index="authors",values="text_reviews_count", aggfunc="sum").sort_values("text_reviews_count",ascending=False)

                                         text_reviews_count
authors
J.K. Rowling/Mary GrandPré                           128006
Stephenie Meyer                                       94265
Markus Zusak/Cao Xuân Việt Khương                     86881
Jodi Picoult                                          79300
Lois Lowry                                            74197
...                                                     ...
Aeschylus/Denys L. Page                                   0
Adrian Guelke/Michael Cox/Fiona Stephen                   0
Adolfo Bioy Casares                                       0
Agatha Christie/Rosemary Leach                            0
Alan Hausman/Paul Tidman                                  0

[6639 rows x 1 columns]

In [14]:
men4 = pd.read_csv("data/men2004.csv")

In [15]:
men8 = pd.read_csv("data/men2008.csv")

In [20]:
men_outer= men4.merge(men8, how="outer",on="Athlete",suffixes=['_2004','_2008'],indicator=True)

In [22]:
men_outer['_merge'].value_counts()

_merge
right_only    46
left_only     43
both          16
Name: count, dtype: int64

In [23]:
men_outer[men_outer['_merge'] == "right_only"]

                      Athlete  Medals_2004  Medals_2008      _merge
0              ADRIAN, Nathan          NaN          1.0  right_only
1               BERENS, Ricky          NaN          1.0  right_only
2              BERNARD, Alain          NaN          3.0  right_only
3         BOUSQUET, Frederick          NaN          1.0  right_only
6                BRITS, Grant          NaN          1.0  right_only
7               BRODIE, Leith          NaN          2.0  right_only
8              CALLUS, Ashley          NaN          1.0  right_only
10             CAVIC, Milorad          NaN          1.0  right_only
12         CIELO FILHO, Cesar          NaN          2.0  right_only
13             COCHRANE, Ryan          NaN          1.0  right_only
18            DELANEY, Ashley          NaN          1.0  right_only
24               FFROST, Nick          NaN          1.0  right_only
26              FUJII, Takuro          NaN          1.0  right_only
28              GILOT, Fabien          NaN          1.0  right_only
30              GREVERS, Matt          NaN          3.0  right_only
35             IZOTOV, Danila          NaN          1.0  right_only
37              JONES, Cullen          NaN          1.0  right_only
45           LAGUNOV, Evgeniy          NaN          1.0  right_only
46        LAUTERSTEIN, Andrew          NaN          3.0  right_only
47            LEVEAUX, Amaury          NaN          2.0  right_only
49          LOBINTSEV, Nikita          NaN          1.0  right_only
51               LURZ, Thomas          NaN          1.0  right_only
53            MALLET, Gregory          NaN          1.0  right_only
55           MATSUDA, Takeshi          NaN          1.0  right_only
57          MELLOULI, Oussama          NaN          1.0  right_only
58         MIYASHITA, Junichi          NaN          1.0  right_only
60            MURPHY, Patrick          NaN          2.0  right_only
62        OEN, Alexander Dale          NaN          1.0  right_only
64               PALMER, Kirk          NaN          1.0  right_only
65              PARK, Taehwan          NaN          2.0  right_only
71                 PINE, Adam          NaN          1.0  right_only
72        POLISHCHUK, Mikhail          NaN          1.0  right_only
73           RICKARD, Brenton          NaN          2.0  right_only
77            SATO, Hisayoshi          NaN          1.0  right_only
80        SPRENGER, Christian          NaN          1.0  right_only
82            STEIMETZ, Boris          NaN          1.0  right_only
84           STOECKEL, Hayden          NaN          2.0  right_only
85      SUKHORUKOV, Alexander          NaN          1.0  right_only
86            SULLIVAN, Eamon          NaN          3.0  right_only
87              TARGETT, Matt          NaN          2.0  right_only
91   VAN DER WEIJDEN, Maarten          NaN          1.0  right_only
95         VYATCHANIN, Arkady          NaN          2.0  right_only
97             WALTERS, David          NaN          1.0  right_only
98        WEBER-GALE, Garrett          NaN          2.0  right_only
99      WILDMAN-TOBRINER, Ben          NaN          1.0  right_only
103                ZHANG, Lin          NaN          1.0  right_only