In [2]:
import numpy as np

In [2]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [3]:
np.random.rand(3,2)

array([[0.56455116, 0.35481856],
       [0.89060714, 0.94049707],
       [0.09431123, 0.21845982]])

In [6]:
arr = np.arange(25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
arr[[1,3],0:3:2]

array([[ 5,  7],
       [15, 17]])

In [19]:
a = np.array([1,2,3])

In [24]:
a = np.append(a,4)

In [25]:
np.insert(a,1,12)

array([ 1, 12,  2,  3,  4])

In [26]:
x,y = np.split(a,2)

In [27]:
import pandas as pd

In [28]:
import os 
os.listdir()

['.git',
 '.ipynb_checkpoints',
 'datanaylsismost.ipynb',
 'ecommerce-casestudy.ipynb',
 'ecommerce-purchases.csv',
 'people.csv',
 'people_data.xlsx',
 'pi_digits.txt',
 'programming.txt',
 'Salaries.csv',
 'students.csv',
 'student_eda_dataset.csv',
 'test_pytohn.ipynb',
 'Untitled.ipynb']

In [29]:
salaries = pd.read_csv('Salaries.csv')

C:\Users\LORD\AppData\Local\Temp\ipykernel_2756\1908446028.py:1: DtypeWarning: Columns (3: BasePay, 4: OvertimePay, 5: OtherPay, 6: Benefits, 12: Status) have mixed types. Specify dtype option on import or set low_memory=False.
  salaries = pd.read_csv('Salaries.csv')

In [30]:
salaries.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [31]:
salaries.info()

<class 'pandas.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  str
 2   JobTitle          148654 non-null  str
 3   BasePay           148049 non-null  object
 4   OvertimePay       148654 non-null  object
 5   OtherPay          148654 non-null  object
 6   Benefits          112495 non-null  object
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  str
 12  Status            38119 non-null   str
dtypes: float64(3), int64(2), object(4), str(4)
memory usage: 14.7+ MB

In [32]:
salaries.describe()

                  Id       TotalPay  TotalPayBenefits           Year  Notes
count  148654.000000  148654.000000     148654.000000  148654.000000    0.0
mean    74327.500000   74768.321972      93692.554811    2012.522643    NaN
std     42912.857795   50517.005274      62793.533483       1.117538    NaN
min         1.000000    -618.130000       -618.130000    2011.000000    NaN
25%     37164.250000   36168.995000      44065.650000    2012.000000    NaN
50%     74327.500000   71426.610000      92404.090000    2013.000000    NaN
75%    111490.750000  105839.135000     132876.450000    2014.000000    NaN
max    148654.000000  567595.430000     567595.430000    2014.000000    NaN

In [33]:
salaries.isna().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                605
OvertimePay              0
OtherPay                 0
Benefits             36159
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              110535
dtype: int64

In [37]:
salaries["BasePay"] = pd.to_numeric(
    salaries["BasePay"],
    errors="coerce"
)

In [39]:
salaries["BasePay"].mean()

np.float64(66325.44884048769)

In [40]:
salaries.describe()

,Id,BasePay,TotalPay,TotalPayBenefits,Year,Notes
count,148654.000000,148045.000000,148654.000000,148654.000000,148654.000000,0.0
mean,74327.500000,66325.448840,74768.321972,93692.554811,2012.522643,NaN
std,42912.857795,42764.635495,50517.005274,62793.533483,1.117538,NaN
min,1.000000,-166.010000,-618.130000,-618.130000,2011.000000,NaN
25%,37164.250000,33588.200000,36168.995000,44065.650000,2012.000000,NaN
50%,74327.500000,65007.450000,71426.610000,92404.090000,2013.000000,NaN
75%,111490.750000,94691.050000,105839.135000,132876.450000,2014.000000,NaN
max,148654.000000,319275.010000,567595.430000,567595.430000,2014.000000,NaN

In [42]:
salaries['OvertimePay'] = pd.to_numeric(
    salaries['OvertimePay'],
    errors="coerce"
)

In [43]:
salaries['OvertimePay'].max()

np.float64(245131.88)

In [45]:
salaries[salaries['EmployeeName'] == 'JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [52]:
salaries[salaries['TotalPayBenefits'] == salaries['TotalPayBenefits'].max()
]['EmployeeName']

0    NATHANIEL FORD
Name: EmployeeName, dtype: str

In [61]:
salaries[(salaries['Year'] == 2011) | (salaries['Year'] == 2014)]['BasePay'].mean()

np.float64(65119.3541968012)

In [62]:
salaries.keys()

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='str')

In [64]:
salaries['JobTitle'].nunique()

2159

In [68]:
salaries['JobTitle'].value_counts().head()

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

In [77]:
salaries[salaries['Year'] == 2013]['JobTitle'].value_counts().loc[lambda x: x == 1].sum()

np.int64(202)

In [84]:
salaries['JobTitle'].str.contains("Chief", na=False).sum()

np.int64(423)

In [86]:
salaries['ntitles'] = salaries['JobTitle'].apply(len)
salaries['ntitles']

0         46
1         31
2         31
3         36
4         44
          ..
148649     9
148650    12
148651    12
148652    12
148653    26
Name: ntitles, Length: 148654, dtype: int64