In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
cars = pd.read_csv("data/mpg-unclean.csv")

In [3]:
cars.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name
0,18.0,8,307.0,130.0 hp,3504,12.0,70,United States,chevrolet chevelle malibu
1,15.0,8,350.0,165.0 hp,3693,11.5,70,United States,buick skylark 320
2,18.0,8,318.0,150.0 hp,3436,11.0,70,United States,plymouth satellite
3,16.0,8,304.0,150.0 hp,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0 hp,3449,10.5,70,usa,FORD TORINO

In [4]:
cars.info()

<class 'pandas.DataFrame'>
RangeIndex: 329 entries, 0 to 328
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           329 non-null    float64
 1   cylinders     329 non-null    int64
 2   displacement  329 non-null    float64
 3   horsepower    329 non-null    str
 4   weight        329 non-null    int64
 5   acceleration  329 non-null    float64
 6   model year    329 non-null    int64
 7   origin        329 non-null    str
 8   name          329 non-null    str
dtypes: float64(3), int64(3), str(3)
memory usage: 23.3 KB

In [5]:
cars.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
name            0
dtype: int64

In [6]:
cars.describe()

,mpg,cylinders,displacement,weight,acceleration,model year
count,329.000000,329.000000,329.000000,329.000000,329.000000,329.000000
mean,21.655199,5.802432,217.004559,3229.082067,15.400000,104.495441
std,7.294651,1.719825,104.719009,1376.306985,2.922756,232.498690
min,0.060606,4.000000,68.000000,1800.000000,8.000000,70.000000
25%,16.000000,4.000000,121.000000,2464.000000,13.500000,73.000000
50%,20.200000,6.000000,200.000000,3102.000000,15.400000,76.000000
75%,26.000000,8.000000,305.000000,3821.000000,17.000000,79.000000
max,44.300000,8.000000,455.000000,23000.000000,24.800000,1973.000000

In [5]:
cars.rename(columns={
   'model year':'model_year'
},inplace=True)

In [6]:
cars.origin.value_counts()

origin
usa              254
europe            72
United States      3
Name: count, dtype: int64

In [9]:
cars['origin'] = cars['origin'].replace({
    'United States': 'usa'
})

In [10]:
cars.origin.value_counts()

origin
usa       257
europe     72
Name: count, dtype: int64

In [14]:
cars.horsepower = cars.horsepower.str.split(' ').str.get(0)

In [17]:
cars.horsepower.unique()

array(['130.0', '165.0', '150.0', '140.0', '198.0', '220.0', '215.0',
       '225.0', '190.0', '170.0', '160.0', '95.0', '97.0', '85.0', '46.0',
       '87.0', '90.0', '113.0', '200.0', '210.0', '193.0', 'Not', '100.0',
       '105.0', '88.0', '175.0', '153.0', '180.0', '110.0', '72.0',
       '86.0', '70.0', '76.0', '60.0', '80.0', '54.0', '208.0', '155.0',
       '112.0', '69.0', '145.0', '137.0', '158.0', '167.0', '107.0',
       '230.0', '49.0', '75.0', '91.0', '83.0', '67.0', '78.0', '148.0',
       '129.0', '71.0', '98.0', '115.0', '81.0', '92.0', '79.0', '120.0',
       '152.0', '52.0', '102.0', '58.0', '96.0', '149.0', '89.0', '63.0',
       '48.0', '66.0', '139.0', '68.0', '103.0', '125.0', '133.0',
       '138.0', '135.0', '142.0', '77.0', '62.0', '84.0', '64.0', '65.0',
       '74.0', '82.0'], dtype=object)

In [18]:
cars.horsepower = pd.to_numeric(
    cars.horsepower,
    errors="coerce"
)

In [19]:
cars.describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year
count,329.000000,329.000000,329.000000,323.000000,329.000000,329.000000,329.000000
mean,21.655199,5.802432,217.004559,111.185759,3229.082067,15.400000,104.495441
std,7.294651,1.719825,104.719009,39.846088,1376.306985,2.922756,232.498690
min,0.060606,4.000000,68.000000,46.000000,1800.000000,8.000000,70.000000
25%,16.000000,4.000000,121.000000,83.500000,2464.000000,13.500000,73.000000
50%,20.200000,6.000000,200.000000,100.000000,3102.000000,15.400000,76.000000
75%,26.000000,8.000000,305.000000,141.000000,3821.000000,17.000000,79.000000
max,44.300000,8.000000,455.000000,230.000000,23000.000000,24.800000,1973.000000

In [23]:
cars.name = cars.name.str.lower().str.strip()

In [25]:
cars.model_year.value_counts()

model_year
73      33
76      32
70      29
78      28
79      27
75      26
71      25
72      23
82      23
74      22
77      22
80      17
81      17
1973     5
Name: count, dtype: int64

In [26]:
cars.model_year = cars.model_year.replace({
    1973:73
})

In [27]:
cars.model_year.value_counts()

model_year
73    38
76    32
70    29
78    28
79    27
75    26
71    25
72    23
82    23
74    22
77    22
80    17
81    17
Name: count, dtype: int64

In [29]:
cars.weight.min()

np.int64(1800)

In [34]:
cars.loc[cars.weight.idxmax(),'weight'] = 2300

In [35]:
cars.weight.describe()

count     329.000000
mean     3166.164134
std       837.344920
min      1800.000000
25%      2451.000000
50%      3086.000000
75%      3820.000000
max      5140.000000
Name: weight, dtype: float64

In [38]:
cars.mpg.min()

np.float64(0.0606060606060606)

In [40]:
cars.loc[cars.mpg.idxmin(),'mpg'] = 1 / cars.loc[cars.mpg.idxmin(),'mpg']

In [41]:
cars.mpg.min()

np.float64(9.0)

In [43]:
cars.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

In [46]:
cars.keys()

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='str')

In [47]:
cars.duplicated(subset=['name']).sum()

np.int64(88)

In [50]:
cars.duplicated().sum()

np.int64(10)

In [49]:
cars[cars.duplicated(keep=False)]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
11,14.0,8,340.0,160.0,3609,8.0,70,usa,plymouth 'cuda 340
20,25.0,4,104.0,95.0,2375,17.5,70,europe,saab 99e
31,17.0,6,250.0,100.0,3329,15.5,71,usa,chevrolet chevelle malibu
79,12.0,8,429.0,198.0,4952,11.5,73,usa,mercury marquis brougham
94,13.0,8,360.0,170.0,4654,13.0,73,usa,plymouth custom suburb
117,16.0,6,258.0,110.0,3632,18.0,74,usa,amc matador
161,27.0,4,101.0,83.0,2202,15.3,76,europe,renault 12tl
165,14.5,8,351.0,152.0,4215,12.8,76,usa,ford gran torino
268,24.3,4,151.0,90.0,3003,20.1,80,usa,amc concord
308,25.0,6,181.0,110.0,2945,16.4,82,usa,buick century limited
319,25.0,4,104.0,95.0,2375,17.5,70,europe,saab 99e
320,14.0,8,340.0,160.0,3609,8.0,70,usa,plymouth 'cuda 340
321,13.0,8,360.0,170.0,4654,13.0,73,usa,plymouth custom suburb
322,16.0,6,258.0,110.0,3632,18.0,74,usa,amc matador
323,24.3,4,151.0,90.0,3003,20.1,80,usa,amc concord
324,12.0,8,429.0,198.0,4952,11.5,73,usa,mercury marquis brougham
325,27.0,4,101.0,83.0,2202,15.3,76,europe,renault 12tl
326,17.0,6,250.0,100.0,3329,15.5,71,usa,chevrolet chevelle malibu
327,14.5,8,351.0,152.0,4215,12.8,76,usa,ford gran torino
328,25.0,6,181.0,110.0,2945,16.4,82,usa,buick century limited

In [51]:
cars['horsepower'] = cars['horsepower'].fillna(
    cars['horsepower'].median()
)

In [52]:
cars.describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year
count,329.000000,329.000000,329.000000,329.000000,329.000000,329.000000,329.000000
mean,21.705167,5.802432,217.004559,110.981763,3166.164134,15.400000,75.620061
std,7.201994,1.719825,104.719009,39.508408,837.344920,2.922756,3.640686
min,9.000000,4.000000,68.000000,46.000000,1800.000000,8.000000,70.000000
25%,16.000000,4.000000,121.000000,84.000000,2451.000000,13.500000,73.000000
50%,20.200000,6.000000,200.000000,100.000000,3086.000000,15.400000,76.000000
75%,26.000000,8.000000,305.000000,140.000000,3820.000000,17.000000,79.000000
max,44.300000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000

In [53]:
cars = cars.drop_duplicates()

In [54]:
cars.describe()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year
count,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000
mean,21.796865,5.789969,215.891850,110.485893,3155.962382,15.418495,75.655172
std,7.228924,1.720143,104.360203,39.460182,834.343834,2.905785,3.628187
min,9.000000,4.000000,68.000000,46.000000,1800.000000,8.000000,70.000000
25%,16.000000,4.000000,121.000000,83.500000,2440.500000,13.500000,73.000000
50%,20.300000,6.000000,200.000000,100.000000,3085.000000,15.400000,76.000000
75%,26.450000,8.000000,304.500000,140.000000,3802.500000,17.000000,79.000000
max,44.300000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000