In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
titanic = sns.load_dataset("titanic")

In [3]:
titanic.keys()

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [4]:
titanic.groupby("class").groups

{'First': [1, 3, 6, 11, 23, 27, 30, 31, 34, 35, 52, 54, 55, 61, 62, 64, 83, 88, 92, 96, 97, 102, 110, 118, 124, 136, 137, 139, 151, 155, 166, 168, 170, 174, 177, 185, 187, 194, 195, 209, 215, 218, 224, 230, 245, 248, 252, 256, 257, 258, 262, 263, 268, 269, 270, 273, 275, 284, 290, 291, 295, 297, 298, 299, 305, 306, 307, 309, 310, 311, 318, 319, 325, 329, 331, 332, 334, 336, 337, 339, 341, 351, 356, 366, 369, 370, 373, 375, 377, 380, 383, 390, 393, 412, 430, 434, 435, 438, 445, 447, ...], 'Second': [9, 15, 17, 20, 21, 33, 41, 43, 53, 56, 58, 66, 70, 72, 78, 84, 98, 99, 117, 120, 122, 123, 133, 134, 135, 144, 145, 148, 149, 150, 161, 178, 181, 183, 190, 191, 193, 199, 211, 213, 217, 219, 221, 226, 228, 232, 234, 236, 237, 238, 239, 242, 247, 249, 259, 265, 272, 277, 288, 292, 303, 308, 312, 314, 316, 317, 322, 323, 327, 340, 342, 343, 344, 345, 346, 357, 361, 385, 387, 389, 397, 398, 399, 405, 407, 413, 416, 417, 418, 426, 427, 432, 437, 439, 440, 443, 446, 450, 458, 463, ...], 'Third': [0, 2, 4, 5, 7, 8, 10, 12, 13, 14, 16, 18, 19, 22, 24, 25, 26, 28, 29, 32, 36, 37, 38, 39, 40, 42, 44, 45, 46, 47, 48, 49, 50, 51, 57, 59, 60, 63, 65, 67, 68, 69, 71, 73, 74, 75, 76, 77, 79, 80, 81, 82, 85, 86, 87, 89, 90, 91, 93, 94, 95, 100, 101, 103, 104, 105, 106, 107, 108, 109, 111, 112, 113, 114, 115, 116, 119, 121, 125, 126, 127, 128, 129, 130, 131, 132, 138, 140, 141, 142, 143, 146, 147, 152, 153, 154, 156, 157, 158, 159, ...]}

In [5]:
titanic.groupby("class").get_group('First')

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [6]:
titanic.groupby("class")['survived'].count()

class
First     216
Second    184
Third     491
Name: survived, dtype: int64

In [8]:
titanic.groupby("sex")['age'].count()

sex
female    261
male      453
Name: age, dtype: int64

In [3]:
titanic.groupby(['sex','class']).get_group(('female','Third'))

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
863,0,3,female,NaN,8,2,69.5500,S,Third,woman,False,NaN,Southampton,no,False
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [5]:
titanic.groupby(['sex','class']).sum(numeric_only=True)

               survived  pclass      age  sibsp  parch       fare  adult_male  \
sex    class
female First         91      94  2942.00     52     43  9975.8250           0
       Second        70     152  2125.50     37     46  1669.7292           0
       Third         72     432  2218.50    129    115  2321.1086           0
male   First         45     122  4169.42     38     34  8201.5875         119
       Second        17     216  3043.33     37     24  2132.1125          99
       Third         47    1041  6706.42    173     78  4393.5865         319

               alone
sex    class
female First      34
       Second     32
       Third      60
male   First      75
       Second     72
       Third     264

In [10]:
titanic['mean_age'] = titanic.groupby(['sex','pclass'])['age'].transform('mean')
titanic['mean_age']

0      26.507589
1      34.611765
2      21.750000
3      34.611765
4      26.507589
         ...
886    30.740707
887    34.611765
888    21.750000
889    41.281386
890    26.507589
Name: mean_age, Length: 891, dtype: float64

In [11]:
titanic.age.fillna(titanic.mean_age)

0      22.00
1      38.00
2      26.00
3      35.00
4      35.00
       ...
886    27.00
887    19.00
888    21.75
889    26.00
890    32.00
Name: age, Length: 891, dtype: float64

In [13]:
from scipy.stats import zscore

In [15]:
titanic.groupby("pclass")['fare'].transform(zscore)

0     -0.546105
1     -0.164598
2     -0.488737
3     -0.397125
4     -0.478113
         ...
886   -0.572621
887   -0.692526
888    0.830727
889   -0.692526
890   -0.503610
Name: fare, Length: 891, dtype: float64

In [16]:
omlympic = pd.read_csv("data/olympics.csv")

In [17]:
omlympic.info()

<class 'pandas.DataFrame'>
RangeIndex: 29216 entries, 0 to 29215
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   City          29216 non-null  str
 1   Edition       29216 non-null  int64
 2   Sport         29216 non-null  str
 3   Discipline    29216 non-null  str
 4   Athlete       29216 non-null  str
 5   NOC           29216 non-null  str
 6   Gender        29216 non-null  str
 7   Event         29216 non-null  str
 8   Event_gender  29216 non-null  str
 9   Medal         29216 non-null  str
dtypes: int64(1), str(9)
memory usage: 2.2 MB

In [21]:
omlympic.groupby('City')['Medal'].value_counts()

City       Medal
Amsterdam  Bronze    242
           Silver    239
           Gold      229
Antwerp    Gold      497
           Silver    446
                    ...
Sydney     Silver    667
           Gold      663
Tokyo      Bronze    343
           Silver    337
           Gold      330
Name: count, Length: 66, dtype: int64

In [22]:
omlympic.keys()

Index(['City', 'Edition', 'Sport', 'Discipline', 'Athlete', 'NOC', 'Gender',
       'Event', 'Event_gender', 'Medal'],
      dtype='str')

In [23]:
omlympic.groupby('Edition')['Gender'].value_counts()

Edition  Gender
1896     Men        151
1900     Men        501
         Women       11
1904     Men        458
         Women       12
1908     Men        789
         Women       15
1912     Men        855
         Women       30
1920     Men       1255
         Women       43
1924     Men        833
         Women       51
1928     Men        615
         Women       95
1932     Men        555
         Women       60
1936     Men        791
         Women       84
1948     Men        718
         Women       96
1952     Men        750
         Women      139
1956     Men        739
         Women      146
1960     Men        737
         Women      145
1964     Men        820
         Women      190
1968     Men        819
         Women      212
1972     Men        947
         Women      238
1976     Men        924
         Women      381
1980     Men        958
         Women      429
1984     Men        973
         Women      486
1988     Men       1011
         Women      535
1992     Men       1105
         Women      600
1996     Men       1082
         Women      777
2000     Men       1126
         Women      889
2004     Men       1099
         Women      899
2008     Men       1110
         Women      932
Name: count, dtype: int64